insert into public.relic_catalog (relic_id, display_name, rarity, xp_reward)
values
  ('cosmic-shard', 'Cosmic Shard', 'legendary', 100),
  ('nebula-crystal', 'Nebula Crystal', 'epic', 75),
  ('star-fragment', 'Star Fragment', 'rare', 50),
  ('aurora-gem', 'Aurora Gem', 'epic', 75),
  ('eclipse-orb', 'Eclipse Orb', 'epic', 75),
  ('hidden-relic', 'Forgotten Idol', 'legendary', 100),
  ('abyssal-bubble', 'Abyssal Bubble', 'rare', 50),
  ('storm-core-element', 'Storm Core', 'legendary', 100),
  ('lunar-tablet', 'Lunar Tablet', 'rare', 50),
  ('phoenix-ember-crystal', 'Phoenix Ember Crystal', 'legendary', 100),
  ('mystical-oracle-eye', 'Mystical Oracle Eye', 'epic', 75),
  ('emerald-heart', 'Emerald Heart', 'epic', 75),
  ('magma-crown', 'Magma Crown', 'legendary', 100),
  ('radiant-solar-sun', 'Radiant Solar Sun', 'epic', 75),
  ('ancient-mystical-coin', 'Ancient Mystical Coin', 'rare', 50),
  ('fossil-fang', 'Fossil Fang', 'rare', 50),
  ('dreamcap-spore', 'Dreamcap Spore', 'rare', 50),
  ('levitating-armored-seed', 'Levitating Armored Seed', 'epic', 75),
  ('dragon-flame-scale', 'Dragon Flame Scale', 'legendary', 100),
  ('elegant-glass-flower', 'Elegant Glass Flower', 'epic', 75),
  ('titan-stone', 'Titan Stone', 'rare', 50),
  ('premium-siren-shell', 'Siren Shell', 'legendary', 100),
  ('tidekeeper-trident', 'Tidekeeper Trident', 'legendary', 100),
  ('frost-rune-ice-tablet', 'Frost Rune Ice Tablet', 'epic', 75),
  ('meteor-heart', 'Meteor Heart', 'legendary', 100),
  ('eternal-flame', 'Eternal Flame', 'legendary', 100),
  ('saturn-seal', 'Saturn Seal', 'epic', 75),
  ('astral-beacon', 'Astral Beacon', 'epic', 75),
  ('solar-crown', 'Solar Crown', 'legendary', 100),
  ('dark-moon', 'Dark Moon', 'epic', 75),
  ('comet-tear', 'Comet Tear', 'rare', 50),
  ('ancient-temple-key', 'Ancient Temple Key', 'rare', 50),
  ('celestial-key', 'Celestial Key', 'legendary', 100),
  ('ancient-prophecy-scroll', 'Ancient Prophecy Scroll', 'epic', 75),
  ('eternal-hourglass', 'Eternal Hourglass', 'legendary', 100),
  ('sentinel-crest', 'Sentinel Crest', 'epic', 75),
  ('crimson-dragon-soul', 'Crimson Dragon Soul', 'legendary', 100),
  ('ancient-spirit-mask', 'Ancient Spirit Mask', 'epic', 75),
  ('crown-of-ages', 'Crown of Ages', 'legendary', 100),
  ('creation-tear', 'Creation Tear', 'legendary', 100),
  ('comic-egg', 'Comic Egg', 'epic', 75),
  ('prismatic-shard', 'Prismatic Shard', 'legendary', 100),
  ('void-pearl', 'Void Pearl', 'legendary', 100)
on conflict (relic_id) do update
set
  display_name = excluded.display_name,
  rarity = excluded.rarity,
  xp_reward = excluded.xp_reward,
  updated_at = now();
